#!/bin/bash

version=1.0.1

echo -e "Github SSH setup (GSSHS) v$version\n(C) 2024-2025, Alex Free (3-BSD)\n\n"

if [ $# -ne 2 ]; then
	echo -e "Error: 2 arguments are required.\nUsage:\n\ngsshs <github account email> <github user name>"
	exit 1
fi

if ! command -v git &> /dev/null; then
    echo "Error: git is not installed."
    exit 1
fi

git config --global user.name "$2"
git config --global user.email "$1"

if [[ "$(uname)" -ne "Darwin" ]]; then

    if ! command -v xclip &> /dev/null; then
        echo "Info: xclip is not installed."
        
        if command -v apt &> /dev/null; then
            echo "Info: APT package manager detected. Root privilages are required to installed xclip:"
            sudo apt update
            sudo apt install -y xclip
        elif command -v dnf &> /dev/null; then
            echo "Info: DNF package manager detected. Root privilages are required to installed xclip:"
            sudo dnf update
            sudo dnf install -y xclip
        else
            echo "Error: Unknown package manager. xclip can not be installed automatically. Please install xclip before using gsshs."
            exit 1
        fi
    else
        echo "Found xclip."
    fi
fi

ssh-keygen -t ed25519 -C "$1" -N '' -f ~/.ssh/id_ed25519 <<< y

echo "SSH key copied to clibboard, paste it in Github."

if [[ "$(uname)" == "Darwin" ]]; then
    cat ~/.ssh/id_ed25519.pub | pbcopy
    open "https://github.com/settings/keys"
else
    cat ~/.ssh/id_ed25519.pub | xclip -selection c
    xdg-open "https://github.com/settings/keys"
fi
